# pull this docker image and get flag from file in immediate directory (captain)

# locate the image file (name is Location flag)

# loading, extract the image and mount it with the password provided in the challenge prompt, then get the flag (loading)

FROM ubuntu:22.04

COPY captain.sh .
COPY flag_image.iso /root/

CMD bash captain.sh